import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import clsx from 'clsx'
import { GeekChip, GeekDetail, GeekPanel, GeekToolbar } from './shared'

const LAYERS = [
  {
    id: 'secrets',
    label: 'Unlock secrets',
    hint: 'Customer-held, never stored by Kryptic',
    items: [
      {
        id: 'passphrase',
        label: 'Vault passphrase',
        chip: 'human',
        title: 'Vault passphrase',
        text: 'Typed in the browser. Argon2id (64 MiB, 3 iterations, parallelism 4, parameter set v1) turns it into a 32-byte wrap key. That key opens the envelope labeled vaultpass_v1, which holds the member P-256 private scalar. Wrong passphrase fails GCM authentication. Kryptic cannot reset it.',
      },
      {
        id: 'client-secret',
        label: 'Machine client secret',
        chip: 'ci',
        title: 'Machine client secret',
        text: '32 random bytes, shown once as base64url. The server stores only an Argon2id hash. The same parameter set derives the wrap key that opens machinesecret_v1. Lose it and you rotate the identity.',
      },
      {
        id: 'device',
        label: 'Device key pair',
        chip: 'daemon',
        title: 'Device key pair',
        text: 'Generated by the daemon at login and stored in the OS credential store. The public key is registered during the device flow. An admin seals the org key to it on approval. There is no passphrase on this path.',
      },
      {
        id: 'recovery',
        label: 'Recovery code',
        chip: 'kit',
        title: 'Emergency Kit recovery code',
        text: '160 bits of Crockford base32, grouped as eight blocks of four, shown once. Argon2id unwraps the recovery private key (recovery_v1), which opens the recovery grant. If every admin loses their passphrase and this code, the values are gone.',
      },
    ],
  },
  {
    id: 'party',
    label: 'Party P-256 key',
    hint: 'Private scalar is client-side only, stored wrapped',
    items: [
      {
        id: 'party-key',
        label: 'Member / device / machine / recovery key',
        chip: 'P-256',
        title: 'Party key pair',
        text: 'Uncompressed SEC1 public point (65 bytes, 0x04 || X || Y) is stored in the clear so an admin can seal to it. The 32-byte private scalar is stored only inside a wrapping envelope the server cannot open. This key never encrypts secret values. It only opens the org-key grant.',
      },
    ],
  },
  {
    id: 'grant',
    label: 'Sealed-box grant',
    hint: 'ECIES delivery of the org key',
    items: [
      {
        id: 'grant-box',
        label: 'sbx.v1.<recipientKeyId>.…',
        chip: 'ECIES',
        title: 'Org-key grant',
        text: 'One sealed box per authorized party. A fresh ephemeral P-256 key, ECDH, HKDF-SHA256 (info = kryptic-sealed-box-v1 || ephPub || recipPub), then AES-256-GCM. Only the matching private key opens it. Revoking a grant stops future delivery. It cannot erase a key a client already held, which is why rotation exists.',
      },
    ],
  },
  {
    id: 'org',
    label: 'Organization key',
    hint: '32 random bytes, plaintext only on clients',
    items: [
      {
        id: 'org-key',
        label: 'Org key (AES-256)',
        chip: '32 B',
        title: 'Organization key',
        text: 'Generated in the initializing admin browser (key_ + 12 hex chars). It is the only key that encrypts secret values. The server stores it solely inside grants. After unlock, clients keep it in memory for the session or the daemon process. It is never written to disk as plaintext.',
      },
    ],
  },
  {
    id: 'values',
    label: 'Secret values',
    hint: 'AES-256-GCM with row-bound associated data',
    items: [
      {
        id: 'envelope',
        label: 'v1.<orgKeyId>.<nonce>.<ct||tag>',
        chip: 'GCM',
        title: 'Secret envelope',
        text: 'The only form a secret value takes on the wire or in the database. Associated data is secret:<definitionId>:env:<environmentId> (lowercase GUIDs). Moving a production ciphertext onto a development row fails the tag. The server can index the envelope. It cannot read it.',
      },
    ],
  },
]

export function KeyHierarchyGraph() {
  const [active, setActive] = useState('org-key')
  const current = LAYERS.flatMap((layer) => layer.items).find((item) => item.id === active)

  return (
    <GeekPanel>
      <GeekToolbar
        eyebrow="Key hierarchy"
        title="What unwraps what"
        hint="Click a layer"
      />

      <div className="px-4 py-5 sm:px-5">
        <div className="space-y-3">
          {LAYERS.map((layer, index) => (
            <div key={layer.id}>
              {index > 0 && (
                <div className="mb-3 flex justify-center" aria-hidden="true">
                  <span className="flex h-6 w-px items-end bg-gradient-to-b from-accent/50 to-accent/10" />
                </div>
              )}
              <p className="mb-1.5 font-mono text-2xs uppercase tracking-[0.16em] text-ink-faint">
                {layer.label}
                <span className="ml-2 normal-case tracking-normal text-ink-faint/80">
                  {layer.hint}
                </span>
              </p>
              <div
                className={clsx(
                  'grid gap-2',
                  layer.items.length > 1 ? 'sm:grid-cols-2' : 'grid-cols-1'
                )}
              >
                {layer.items.map((item) => {
                  const selected = active === item.id
                  return (
                    <button
                      key={item.id}
                      type="button"
                      aria-pressed={selected}
                      onClick={() => setActive(item.id)}
                      className={clsx(
                        'rounded-lg border px-3 py-2.5 text-left transition duration-200',
                        selected
                          ? 'border-signal-violet/45 bg-signal-violet/10'
                          : 'border-edge bg-surface hover:border-edge-lift hover:bg-surface-hover'
                      )}
                    >
                      <span className="flex items-center justify-between gap-2">
                        <span className="font-mono text-xs text-ink">{item.label}</span>
                        <GeekChip tone="violet">{item.chip}</GeekChip>
                      </span>
                    </button>
                  )
                })}
              </div>
            </div>
          ))}
        </div>
      </div>

      <AnimatePresence mode="wait">
        <motion.div
          key={current.id}
          initial={{ opacity: 0, y: 6 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -4 }}
          transition={{ duration: 0.18 }}
        >
          <GeekDetail title={current.title}>
            <p>{current.text}</p>
          </GeekDetail>
        </motion.div>
      </AnimatePresence>
    </GeekPanel>
  )
}
